routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Home Page
Route::get('/', static function () {
    return redirect()->route('auth.login.index');
});

// Auth Pages
Route::group(
    ['prefix' => '/auth', 'as' => 'auth.', 'namespace' => 'Auth'],
    static function () {
        Route::group(
            ['middleware' => 'auth.redirect'],
            static function () {
                // Login
                Route::group(
                    ['prefix' => '/login', 'as' => 'login.'],
                    static function () {
                        // Login Page
                        Route::get('/', 'LoginController@index')
                            ->name('index');

                        // Logging
                        Route::group(
                            ['laroute' => true],
                            static function () {
                                Route::post('/', 'LoginController@ajax')
                                    ->name('ajax');
                            }
                        );
                    }
                );

                // Register
                Route::group(
                    ['prefix' => '/register', 'as' => 'register.'],
                    static function () {
                        // Register Page
                        Route::get('/', 'RegisterController@index')
                            ->name('index');

                        // Verify Page
                        Route::get('/verify/{token}', 'RegisterController@verify')
                            ->name('verify');

                        // Registration
                        Route::group(
                            ['laroute' => true],
                            static function () {
                                Route::post('/', 'RegisterController@ajax')
                                    ->name('ajax');
                            }
                        );
                    }
                );
            }
        );

        // Logout
        Route::group(
            ['middleware' => 'auth.app'],
            static function () {
                Route::get('/logout', 'LogoutController@logout')
                    ->name('logout');
            }
        );
    }
);

// After Logging
Route::group(
    ['as' => 'logged.', 'namespace' => 'Logged', 'middleware' => 'auth.app'],
    static function () {
        // Home Page
        Route::get('/', 'HomeController@index')->name('index');
    }
);

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Auth\Authenticatable;
use Illuminate\Contracts\Auth\Access\Authorizable as AuthorizableContract;
use Illuminate\Contracts\Auth\Authenticatable as AuthenticatableContract;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\HasOne;
use Illuminate\Foundation\Auth\Access\Authorizable;

/**
 * Class User
 * @package App\Models
 *
 * @property int $id
 * @property string $name
 * @property string $email
 * @property string $password
 * @property boolean $active
 * @property boolean $verified
 * @property string $last_visit
 * @property string $email_verified_at
 */
class User extends Model implements AuthenticatableContract, AuthorizableContract
{
    use Authenticatable, Authorizable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name',
        'email',
        'password',
        'active',
        'verified',
        'last_visit',
        'email_verified_at',
    ];

    /**
     * @return HasOne
     */
    public function verify(): HasOne
    {
        return $this->hasOne(VerifyUser::class);
    }
}

app/Models/VerifyUser.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;

/**
 * Class VerifyUser
 * @package App\Models
 *
 * @property User $user_id
 * @property string $token
 */
class VerifyUser extends Model
{
    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'user_id',
        'token',
    ];

    /**
     * @return BelongsTo
     */
    public function user(): BelongsTo
    {
        return $this->belongsTo(User::class, 'user_id');
    }
}

app/helpers.php
<?php

declare(strict_types=1);

use Illuminate\Support\Facades\File;

if (!function_exists('version')) {
    /**
     * @param $fileName
     *
     * @return string
     */
    function version($fileName)
    {
        $path = public_path('assets'.'/'.$fileName);

        return asset($fileName).'?='.(File::lastModified($path));
    }
}

app/Http/Controllers/Logged/HomeController.php
<?php


namespace App\Http\Controllers\Logged;

use App\Base\AuthController;
use Illuminate\View\View;

/**
 * Class HomeController
 * @package App\Http\Controllers\Logged
 */
class HomeController extends AuthController
{
    /**
     * @return View
     */
    public function index(): View
    {
        return view('pages.logged.index');
    }
}

resources/views/layouts/app.blade.php
<!doctype html>
<html lang="{{ app()->getLocale() }}">

<head>

    <!-- Basic Page Needs
    ================================================== -->
    <meta charset="utf-8">
    <title>{{ config('app.name') }} - @yield('title')</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="author" content="Keos Media">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <!-- Fonts
    ================================================== -->
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Poppins:300,400,500,600,700|Roboto:300,400,500,600,700">

    <!-- CSS
    ================================================== -->
    <link rel="stylesheet" href="{{ asset('plugins/bootstrap/bootstrap.min.css') }}">
    <link rel="stylesheet" href="{{ asset('plugins/sweetalert2/sweetalert2.css') }}">
    <link rel="stylesheet" href="{{ version('styles/app.css') }}">

</head>

<body>

<!-- Content
================================================== -->
@section('main-content')
@show

<!-- JS
================================================== -->
<script src="{{ asset('plugins/jquery-3.5.0.min.js') }}"></script>
<script src="{{ asset('plugins/bootstrap/bootstrap.min.js') }}"></script>
<script src="{{ asset('plugins/sweetalert2/sweetalert2.min.js') }}"></script>
<script src="{{ asset('laravel/laroute.js') }}"></script>
<script src="{{ version('plugins/sweetalert2/init.js') }}"></script>
<script src="{{ version('scripts/app.js') }}"></script>
</body>

resources/views/layouts/auth.blade.php
<!doctype html>
<html lang="{{ app()->getLocale() }}">

<head>

    <!-- Basic Page Needs
    ================================================== -->
    <meta charset="utf-8">
    <title>{{ config('app.name') }} - @yield('title')</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="author" content="Keos Media">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <!-- Fonts
    ================================================== -->
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Poppins:300,400,500,600,700|Roboto:300,400,500,600,700">

    <!-- CSS
    ================================================== -->
    <link rel="stylesheet" href="{{ asset('plugins/bootstrap/bootstrap.min.css') }}">
    <link rel="stylesheet" href="{{ asset('plugins/sweetalert2/sweetalert2.css') }}">
    <link rel="stylesheet" href="{{ version('styles/app.css') }}">
    <link rel="stylesheet" href="{{ version('styles/auth.css') }}">

</head>

<body>

<!-- Content
================================================== -->
<div class="auth-container">
    <div class="auth-forms">
        <div class="card">
            <h5 class="card-header info-color white-text text-center py-4">
                <strong>@yield('form-title')</strong>
            </h5>

            <!-- begin:: Form -->
            <div class="card-body px-lg-5">
                @section('main-form')
                @show
            </div>
            <!-- end:: Form -->
        </div>
    </div>
</div>

<!-- JS
================================================== -->
<script src="{{ asset('plugins/jquery-3.5.0.min.js') }}"></script>
<script src="{{ asset('plugins/bootstrap/bootstrap.min.js') }}"></script>
<script src="{{ asset('plugins/sweetalert2/sweetalert2.min.js') }}"></script>
<script src="{{ asset('laravel/laroute.js') }}"></script>
<script src="{{ version('plugins/sweetalert2/init.js') }}"></script>
<script src="{{ version('scripts/app.js') }}"></script>
<script src="{{ version('scripts/auth.js') }}"></script>
</body>

resources/views/layouts/email.blade.php
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xmlns:v="urn:schemas-microsoft-com:vml"
      xmlns:o="urn:schemas-microsoft-com:office:office">
<head>
    <meta content="text/html; charset=utf-8" http-equiv="Content-Type">
    <meta content="IE=edge" http-equiv="X-UA-Compatible">

    <meta content="telephone=no" name="format-detection"/>
    <meta content="width=device-width, initial-scale=1.0" name="viewport"/>

    <title>@yield('subject')</title>

    <!--[if gte mso 9]>
    <xml>
        <o:OfficeDocumentSettings>
            <o:AllowPNG/>
            <o:PixelsPerInch>96</o:PixelsPerInch>
        </o:OfficeDocumentSettings>
    </xml>
    <![endif]-->

    <!--[if mso]>
    <style type="text/css">
        body, table, td {
            font-family: Arial, Helvetica, sans-serif !important;
        }
    </style>
    <![endif]-->
</head>
@section('main-content')
@show
</html>

resources/views/pages/logged/index.blade.php
@extends('layouts.app')
@section('title', 'Strona główna')

@section('main-content')
    <p>Witaj <strong>{{ $user->name }}</strong></p>
    <p><a href="{{ route('auth.logout') }}">Wyloguj się</a></p>
@endsection